Log one line per event

diff --git a/iam-credentials-disabler b/iam-credentials-disabler
--- a/iam-credentials-disabler
+++ b/iam-credentials-disabler
@@ -2,11 +2,11 @@
 
 mode=$1
 
-log_append() {
+log() {
   level=$1
   text=$2
   if [[ "$verbose" == "true" ]] || [[ "$level" == "info" ]]; then
-    output="$output$text"
+    echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") $name $text"
   fi
 }
 
@@ -27,34 +27,35 @@ detect_unused_keys() {
   if [[ $active == true ]]; then
     last_used=$(echo "$user" | jq -r ".access_key_${number}_last_used_date")
     if [[ $last_used == "N/A" || "$(date -d "$last_used" +"%s")" -lt "$expiry" ]]; then
-      log_append debug "  Unused key detected in the credentials report (access_key_${number}: $last_used)\n"
-      log_append debug "  Inspecting user's keys with the API\n"
+      # Unused key detected in the credentials report, inspecting user's keys with the API"
       inspect_user
     else
-      log_append debug "  access_key_${number} is active and used: ($last_used)\n"
+      log debug "access_key_$number is active and used: ($last_used)"
     fi
   fi
 }
 
 inspect_user() {
-  for key in $(aws iam list-access-keys --user-name "${name}" | jq -rc '.AccessKeyMetadata[] | select(.Status == "Active")'); do
+  for key in $(aws iam list-access-keys --user-name "$name" | jq -rc '.AccessKeyMetadata[] | select(.Status == "Active")'); do
     id=$(echo "$key" | jq -r ".AccessKeyId")
-    last_used=$(aws iam get-access-key-last-used --access-key-id "${id}" | jq -r '.AccessKeyLastUsed.LastUsedDate')
+    last_used=$(aws iam get-access-key-last-used --access-key-id "$id" | jq -r '.AccessKeyLastUsed.LastUsedDate')
     if [[ "$last_used" == "null" ]]; then
       created=$(echo "$key" | jq -r ".CreateDate")
       if [[ "$(date -d "$created" +"%s")" -lt "$expiry" ]]; then
-        log_append info "    access_key ${id} never used on an old user ($created)\n"
-        log_append info "    DELETED $id access key\n"
-        aws iam delete-access-key --user-name "${name}" --access-key-id "${id}"
+        log info "DELETE access_key $id never used on an old user ($created)"
+        if ! aws iam delete-access-key --user-name "$name" --access-key-id "$id"; then
+          log info "ERROR: failed to delete access_key $id"
+        fi
       else
-        log_append debug "    access_key ${id} never used, but created recently ($created)\n"
+        log debug "access_key $id never used, but created recently ($created)"
       fi
     elif [[ "$(date -d "$last_used" +"%s")" -lt "$expiry" ]]; then
-      log_append info "    access_key ${id} unused recently ($last_used)\n"
-      log_append info "    DELETED $id access key\n"
-      aws iam delete-access-key --user-name "${name}" --access-key-id "${id}"
+      log info "DELETE access_key $id unused recently ($last_used)\n"
+      if ! aws iam delete-access-key --user-name "$name" --access-key-id "$id"; then
+        log info "ERROR: failed to delete access_key $id"
+      fi
     else
-      log_append debug "    access_key ${id} used recently ($last_used)\n"
+      log debug "access_key $id used recently ($last_used)"
     fi
   done
   user_inspected=true
@@ -70,23 +71,15 @@ expiry=$(date +%s -d "45 days ago")
 report=aws-report.csv
 
 generate_report
-
 headers="$(head -n1 "$report")"
-counter=1
+
 for user in $(yq "$report" -ojson | jq -rc '.[]'); do
   name=$(echo "$user" | jq -r '.user')
-  output=""
-
 
   user_inspected=false
   counter=1
-  while [[ "$headers" == *"access_key_${counter}"* && "$user_inspected" == "false" ]]; do
+  while [[ "$headers" == *"access_key_$counter"* && "$user_inspected" == "false" ]]; do
     detect_unused_keys "$counter"
     ((counter++))
   done
-
-  if [[ "$output" != "" ]]; then
-    printf "$name\n"
-    printf "$output"
-  fi
 done
